version: "2"
services:

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: BD_jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks: [ "BD_Net" ]
  prometheus:
    image: prom/prometheus:latest
    container_name: BD_prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [ "BD_Net" ]
  grafana:
    container_name: BD_grafana
    restart: always
    image: grafana/grafana
    ports:
      - '3005:3000'
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks: [ "BD_Net" ]

networks:
  BD_Net: