global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]